### ISSUE TITLE
Fails to Build

### ISSUE THREAD

**Issue by Mactastic1-5** [psemu/ps2ls#3]
I install OpenTK and it it fails to build with several errors in the console.

**Comment by Mactastic1-5** [comment]
I used a pre-built OpenTK library and it successfully builds.

**Comment by PS2emu** [comment]
I have an earlier version (1.1.0.72) that is quite stable, but only views models and meshes. There isn't any map viewing, no sound browser, or actor browser. Would that be something you would want to have?

**Comment by PS2emu** [comment]
It also doesn't throw up half as many errors/crash as many times as the current version. That's not to say there aren't errors in the background, but they don't show up on the UI and don't cause crashes as frequently.

**Comment by Mactastic1-5** [comment]
I already successfully built the program. The features you mentioned do not work because the only thing that has been created is mostly the UI. I don't get any errors when compiling the current version. Building OpenTK is the issue, use the pre-built OpenTK library. I plan on modifying the program to extend the program's features and support.

**Comment by PS2emu** [comment]
Sorry, should have specified. I meant errors with the program running, not when it compiles. You're welcome to have the earlier version if you want it. 

Good luck with your endeavors.
